export const HOME_PATH = '/'
export const BUSINESS_DETAIL_PATH = '/detail-bisnis/:id'
export const ABOUT_PATH = '/tentang-kami'
export const INSTAGRAM_PATH = 'https://www.instagram.com/yukbantubisnis.online/'
export const GOOGLE_FORM_PATH = 'https://forms.gle/FJvoi2dbzzP4nPLcA'