export const HOME_PATH = '/'
export const BUSINESS_DETAIL_PATH = '/b/:id'
export const ABOUT_PATH = '/tentang-kami'
export const INTERNAL_COOKIE_PATH = '/internal/get-da-cookie'
export const INSTAGRAM_PATH = 'https://www.instagram.com/yukbantubisnis.online/'
export const GOOGLE_FORM_PATH = 'https://forms.gle/FJvoi2dbzzP4nPLcA'
export const SITEMAP_PAGE_PATH = '/sitemap/:page'
export const SITEMAP_PATH = '/sitemap'