# 2xx
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_ACCEPTED = 202
HTTP_STATUS_NON_AUTHORITATIVE_INFO = 203
HTTP_STATUS_NO_CONTENT = 204
HTTP_STATUS_RESET_CONTENT = 205
HTTP_STATUS_PARTIAL_CONTENT = 206
HTTP_STATUS_MULTI_STATUS = 207
HTTP_STATUS_MULTIPLE_CHOICES = 300

# 4xx
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_PAYMENT_REQUIRED = 402
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_METHOD_NOT_ALLOWED = 405
HTTP_STATUS_NOT_ACCEPTABLE = 406
HTTP_STATUS_PROXY_AUTH_REQUIRED = 407
HTTP_STATUS_REQUEST_TIMEOUT = 408
HTTP_STATUS_CONFLICT = 409
HTTP_STATUS_GONE = 410
HTTP_STATUS_LENGTH_REQUIRED = 411
HTTP_STATUS_PRECONDITION_FAILED = 412
HTTP_STATUS_REQUEST_ENTITY_TOO_LARGE = 413
HTTP_STATUS_REQUEST_URI_TOO_LONG = 414
HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415
HTTP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE = 416
HTTP_STATUS_EXPECTATION_FAILED = 417
HTTP_STATUS_TEAPOT = 418
HTTP_STATUS_UNPROCESSABLE_ENTITY = 422
HTTP_STATUS_PRECONDITION_REQUIRED = 428
HTTP_STATUS_TOO_MANY_REQUESTS = 429
HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
