source "https://rubygems.org"

gem "cowsay", "~> 0.3.0"
gem 'mongoid', '~> 7.0.6'
gem 'hanami-validations'
gem 'simple_enum', '~> 2.3.0' , require: 'simple_enum/mongoid'
gem 'fast_jsonapi'
gem 'dotenv'
gem 'unidecoder'
gem 'zache'

gem 'phonelib', '~> 0.6.31'
gem 'csv'