name: deploy website preview
on:
  push

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[preview]')"
    steps:
      - uses: actions/checkout@v2
      - uses: sunderipranata/vercel-action@v.19-patch-sunderi
        id: vercel-deployment
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-deployment.outputs.preview-url }}
