name: deploy website preview
on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19.0.1
        id: now-deployment
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: -c
      - name: preview-url
        run: |
          echo ${{ steps.now-deployment.outputs.preview-url }}
