name: deploy website preview
on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sunderipranata/vercel-action:patch-1
        id: now-deployment
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: preview-url
        run: |
          echo ${{ steps.now-deployment.outputs.preview-url }}
